import { useState, useMemo } from 'react';
import { AppData } from '../types';
import {
  getPulse, getRepSummaries, getCategoryTotals,
  getDormantAccounts, getTopAccounts, getWorstDecline, allReps,
} from '../utils/metrics';
import { generateSignals } from '../utils/signals';
import PulseBar from './sections/PulseBar';
import RepTable from './sections/RepTable';
import CategoryPanel from './sections/CategoryPanel';
import AccountTable from './sections/AccountTable';
import ActivityPanel from './sections/ActivityPanel';
import SignalsPanel from './sections/SignalsPanel';
import { Upload, RefreshCw, ChevronDown } from 'lucide-react';

interface Props {
  data: AppData;
  onReset: () => void;
}

export default function CommandCenter({ data, onReset }: Props) {
  const [selectedRep, setSelectedRep] = useState('');
  const ref = new Date();

  const reps = useMemo(
    () => allReps(data.accounts, data.activity, data.leads).filter(r => !r.toLowerCase().includes('total')),
    [data],
  );

  const pulse       = useMemo(() => getPulse(data.accounts, data.leads, data.activity, ref), [data]);
  const repSummaries = useMemo(() => getRepSummaries(data.accounts, data.activity, ref), [data]);

  const filteredAccounts = useMemo(
    () => (selectedRep ? data.accounts.filter(a => a.rep === selectedRep) : data.accounts),
    [data, selectedRep],
  );

  const categoryTotals = useMemo(() => getCategoryTotals(filteredAccounts), [filteredAccounts]);
  const dormant        = useMemo(() => getDormantAccounts(filteredAccounts, ref), [filteredAccounts]);
  const topAccounts    = useMemo(() => getTopAccounts(filteredAccounts), [filteredAccounts]);
  const worstDecline   = useMemo(() => getWorstDecline(filteredAccounts), [filteredAccounts]);
  const signals        = useMemo(() => generateSignals(data.accounts, data.activity, data.leads, ref), [data]);

  const today = ref.toLocaleDateString('en-US', {
    weekday: 'long', month: 'long', day: 'numeric', year: 'numeric',
  });

  return (
    <div className="min-h-screen bg-[#050d1a]">
      {/* ── Header ── */}
      <header className="border-b border-[#1a3554] bg-[#050d1a]/95 backdrop-blur-sm sticky top-0 z-20">
        <div className="max-w-[1400px] mx-auto px-5 py-2.5 flex items-center gap-4">

          {/* Brand */}
          <div className="flex items-center gap-2 flex-shrink-0">
            <div className="w-7 h-7 rounded-lg bg-blue-600 flex items-center justify-center">
              <RefreshCw className="w-3.5 h-3.5 text-white" />
            </div>
            <span className="text-white font-bold text-sm tracking-tight leading-tight">
              Command<br />Center
            </span>
          </div>

          {/* Date + as-of */}
          <div className="hidden md:flex flex-col min-w-0">
            <div className="flex items-center gap-1.5 text-xs text-slate-400">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 flex-shrink-0" />
              <span className="truncate">{today}</span>
            </div>
            {data.asOf && (
              <span className="text-slate-600 text-xs truncate max-w-xs">{data.asOf.replace(/\s*•\s*Generated by[^•]*/i, '')}</span>
            )}
          </div>

          <div className="flex-1" />

          {/* View toggle: Company Total / By Rep */}
          <div className="flex items-center gap-2">
            <span className="text-slate-500 text-xs hidden sm:block">View:</span>
            <div className="flex bg-slate-900 border border-slate-700 rounded-lg p-0.5">
              <button
                onClick={() => setSelectedRep('')}
                className={`px-3 py-1.5 rounded-md text-xs font-medium transition-all ${
                  !selectedRep ? 'bg-blue-600 text-white shadow' : 'text-slate-400 hover:text-white'
                }`}
              >
                Company Total
              </button>
              <button
                onClick={() => {/* just open the dropdown */}}
                className={`px-3 py-1.5 rounded-md text-xs font-medium transition-all ${
                  selectedRep ? 'bg-blue-600 text-white shadow' : 'text-slate-400 hover:text-white'
                }`}
              >
                By Rep
              </button>
            </div>
          </div>

          {/* Rep dropdown */}
          <div className="relative">
            <select
              value={selectedRep}
              onChange={e => setSelectedRep(e.target.value)}
              className="appearance-none bg-slate-900 border border-slate-700 text-slate-300 text-xs rounded-lg pl-3 pr-7 py-2 cursor-pointer hover:border-slate-600 focus:outline-none focus:border-blue-500 transition-colors"
            >
              <option value="">All Reps</option>
              {reps.map(r => <option key={r} value={r}>{r}</option>)}
            </select>
            <ChevronDown className="absolute right-2 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-500 pointer-events-none" />
          </div>

          {/* File info + upload */}
          <div className="hidden lg:flex items-center gap-2 text-xs text-slate-600 border-l border-slate-800 pl-4">
            <span>{data.accounts.length} accounts</span>
            {data.leads.length > 0 && <span>· {data.leads.length} leads</span>}
          </div>

          <button
            onClick={onReset}
            className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-white border border-slate-700 hover:border-slate-600 rounded-lg px-3 py-1.5 transition-colors flex-shrink-0"
          >
            <Upload className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">Upload</span>
          </button>
        </div>

        {/* Active rep banner */}
        {selectedRep && (
          <div className="bg-blue-600/10 border-t border-blue-600/20 px-5 py-1.5 flex items-center gap-3">
            <span className="text-blue-400 text-xs font-medium">
              Filtering: <strong>{selectedRep}</strong>
            </span>
            <span className="text-slate-500 text-xs">
              {filteredAccounts.length} accounts
            </span>
            <button
              onClick={() => setSelectedRep('')}
              className="ml-auto text-xs text-slate-500 hover:text-slate-300 underline"
            >
              Clear — show all
            </button>
          </div>
        )}
      </header>

      {/* ── Content ── */}
      <main className="max-w-[1400px] mx-auto px-5 py-5 space-y-5">

        <PulseBar pulse={pulse} />

        <RepTable
          reps={repSummaries}
          selectedRep={selectedRep}
          onSelectRep={setSelectedRep}
        />

        <div className="grid grid-cols-1 xl:grid-cols-2 gap-5">
          <CategoryPanel totals={categoryTotals} />
          <AccountTable
            accounts={filteredAccounts}
            dormant={dormant}
            top={topAccounts}
            worst={worstDecline}
            selectedRep={selectedRep}
          />
        </div>

        <ActivityPanel
          activity={data.activity}
          leads={data.leads}
          selectedRep={selectedRep}
        />

        <SignalsPanel signals={signals} />

        <div className="pb-6 text-center text-slate-700 text-xs">
          {data.fileNames.join(' · ')} · loaded {data.uploadedAt.toLocaleTimeString()}
        </div>
      </main>
    </div>
  );
}
